const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const out=path.resolve(__dirname,'../references/hero-v2-bimo-continuity');fs.mkdirSync(out,{recursive:true});const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.argv[2]||process.env.HERO_URL||'http://127.0.0.1:8792';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const results=[];try{
for(const width of [1440,1280]){
 const p=await browser.newPage({viewport:{width,height:width===1440?900:800}});await p.goto(base+'/hero-lab-v2.html?heroDebug');await p.waitForFunction(()=>window.heroV2?.state.character==='live');
 await p.evaluate(()=>{window.firstBimoCanvas=document.querySelector('.bimo canvas');window.firstBimoStage=document.querySelector('.bimo').getBoundingClientRect().toJSON()});
 const verify=()=>p.evaluate(()=>{const e=document.querySelector('.bimo'),c=e.querySelector('canvas'),s=getComputedStyle(c);return {same:c===firstBimoCanvas,rect:e.getBoundingClientRect().toJSON(),initial:firstBimoStage,bitmap:[c.width,c.height],opacity:s.opacity,hidden:s.visibility==='hidden'||s.display==='none',style:e.getAttribute('style')}});
 await p.waitForFunction(()=>heroV2.state.time>=4.25);await p.locator('#motion-control').click();let x=await verify();assert.deepEqual(x.rect,x.initial);assert.equal(x.same,true);const t=await p.evaluate(()=>heroV2.state.time);await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>heroV2.state.time),t);await p.locator('#motion-control').click();await p.waitForFunction(()=>heroV2.state.gate.open);x=await verify();assert.deepEqual(x.rect,x.initial);assert.deepEqual(x.bitmap,[700,860]);assert.equal(x.opacity,'1');assert.equal(x.hidden,false);assert.equal(x.style,null);
 await p.locator('#replay').click();await p.waitForTimeout(600);x=await verify();assert.deepEqual(x.rect,x.initial);assert.equal(x.same,true);assert.equal(await p.locator('.bimo').getAttribute('data-pose'),'awake');
 for(let i=0;i<5;i++)await p.mouse.wheel(0,2400);await p.waitForFunction(()=>heroV2.state.gate.open);x=await verify();assert.deepEqual(x.rect,x.initial);assert.equal(x.same,true);assert.deepEqual(x.bitmap,[700,860]);assert.equal(x.opacity,'1');
 results.push(`${width}: pause/resume, replay, aggressive scroll retain the same visible canvas and exact stage`);await p.close();
}
 const reduced=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});await reduced.goto(base+'/hero-lab-v2.html?heroDebug');await reduced.waitForFunction(()=>window.heroV2?.state.character==='live');assert.equal(await reduced.locator('.bimo canvas').evaluate(c=>getComputedStyle(c).opacity),'1');assert.deepEqual(await reduced.locator('.bimo canvas').evaluate(c=>[c.width,c.height]),[700,860]);results.push('Reduced motion uses the identical stage and bitmap');await reduced.close();
 const cold=await browser.newPage({viewport:{width:1440,height:900},javaScriptEnabled:false});await cold.goto(base+'/hero-lab-v2.html');await cold.waitForTimeout(500);assert.equal(await cold.locator('.awake-still').evaluate(i=>i.complete&&i.naturalWidth>0),true);
 await cold.screenshot({path:path.join(out,'first-paint.png')});results.push('JavaScript-free first paint uses the same decoded Bimo poster and fixed stage');await cold.close();
 console.log(JSON.stringify(results,null,2));fs.writeFileSync(path.join(out,'lifecycle.json'),JSON.stringify(results,null,2));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
